### ISSUE TITLE
file input in branch remains disabled when branch becomes relevant

### ISSUE THREAD

**Issue by MartijnR** [SEL-Columbia/enketo#503]
Reported by Rubem in user forum:

http://awzyb.enketo.formhub.org/webform

So, as you can see, after the last "image question" called "Deseja cadastrar nova foto?", when you choose "yes", another option to put new photo opens (Foto 04 do animal). The button to "choose file" keeps in grey and you can't click it. However, you are able to click where "Foto 04 do animal" is written. Despite this is a little bug, some people of my staff were confused by this, reporting me that they were not able to upload new photos.

**Comment by alxndrsn** [comment]
Have you reported this bug to Chrome?  Still seems to be happening 2 years on!

**Comment by MartijnR** [comment]
I believe I did, but I can't find it. I should have added the link...
